import { VerticalBox , StandardListView, Button } from "std-widgets.slint";
export component Open inherits VerticalBox {
    StandardListView {
        current-item: 0;
        model: [ 
            { text: "Blue"}, { text: "Red" }, { text: "Green" },
            { text: "Yellow" }, { text: "Black"}, { text: "White"},
            { text: "Magenta" }, { text: "Cyan" },
        ];
    }
    Button {
        text: "Open";
    }
    Button {
        text: "Add to workspace";
    }
}