import { VerticalBox , StandardListView, Button } from "std-widgets.slint";

export component Workspaces inherits VerticalBox {
    StandardListView {
        current-item: 0;
        model: [ 
            { text: "Blue"}, { text: "Red" }, { text: "Green" },
            { text: "Yellow" }, { text: "Black"}, { text: "White"},
            { text: "Magenta" }, { text: "Cyan" },
        ];
    }
    Button {
        text: "Add";
    }
    Button {
        text: "Remove";
    }
    Button {
        text: "Edit";
    }
}