import { VerticalBox , StandardListView, GroupBox , LineEdit, Button, HorizontalBox, Switch } from "std-widgets.slint";

export global CloneLogic {
    callback clone(string);
}

export component Clone inherits VerticalBox {
    
    in-out property <bool> upstream-toggled;
    callback clone(string);

    GroupBox {
        title: "Repositories";
        VerticalBox {
            StandardListView {
                current-item: 0;
                model: [ 
                    { text: "Blue"}, { text: "Red" }, { text: "Green" },
                    { text: "Yellow" }, { text: "Black"}, { text: "White"},
                    { text: "Magenta" }, { text: "Cyan" },
                ];
            }
            HorizontalBox {
                Text {
                    vertical-alignment: center;
                    text: "URL:";
                }
                url  := LineEdit {
                    height: 40px;
                    text: "https://github.com/edfloreshz/config";
                }
                Switch {
                    checked <=> root.upstream-toggled;
                    text: "Upstream";
                }
            }
            HorizontalBox {
                visible: root.upstream-toggled;
                Text {
                    vertical-alignment: center;
                    text: "Upstream:";
                }
                upstream  := LineEdit {
                    height: 40px;
                }
            }
            Button {
                text: "Clone";
                clicked => {
                    CloneLogic.clone(url.text)
                }
            }
        }
    }
}