import { VerticalBox, HorizontalBox, StandardListView, LineEdit, ComboBox , Switch, GroupBox} from "std-widgets.slint";

export global ConfigurationLogic {
}

export component Configuration inherits VerticalBox {
    in-out property <bool> custom-editor-enabled;
    in-out property <string> custom-editor;
    
    GroupBox {
        title: "Git";
        VerticalBox {
            HorizontalBox {
                Text {
                    vertical-alignment: center;
                    text: "Service:";
                }
                ComboBox {
                    model: ["GitHub", "GitLab"];
                }
            }
            HorizontalBox {
                Text {
                    vertical-alignment: center;
                    text: "Username:";
                }
                custom-editor-input := LineEdit {
                    height: 40px;
                    text <=> root.custom-editor;
                }
            }
        }
    }
    GroupBox {
        title: "Editor";
        VerticalBox {
            HorizontalBox {
                ComboBox {
                    enabled: !root.custom-editor-enabled;
                    model: ["Vim", "VSCode", "Helix"];
                }
                Switch {
                    checked <=> root.custom-editor-enabled;
                    text: "Custom";
                }
            }
            HorizontalBox {
                visible: root.custom-editor-enabled;
                Text {
                    vertical-alignment: center;
                    text: "Editor command:";
                }
                LineEdit {
                    height: 40px;
                }
            }
        }
    }
    
}