import { Button, VerticalBox, HorizontalBox, GroupBox, TabWidget, CheckBox } from "std-widgets.slint";
import { Clone } from "pages/clone.slint";
import { Open } from "pages/open.slint";
import { Workspaces } from "pages/workspaces.slint";
import { Configuration } from "pages/configuration.slint";

export component AppWindow inherits Window {
    VerticalBox {
        GroupBox {
            title: "Devmode";
    
            TabWidget {
                Tab {
                    title: "Clone";
                    Clone {}
                }
    
                Tab {
                    title: "Open";
                    Open {}
                }
    
                Tab {
                    title: "Workspaces";
                    Workspaces {}
                }

                Tab {
                    title: "Configuration";
                    Configuration {
                        custom-editor: false;
                    }
                }
            }
        }
    }
}
