import { Button, VerticalBox, HorizontalBox, GroupBox, TabWidget, CheckBox } from "std-widgets.slint";
import { Clone, CloneLogic } from "pages/clone.slint";
import { Open, OpenLogic } from "pages/open.slint";
import { Workspaces, WorkspacesLogic } from "pages/workspaces.slint";
import { Configuration, ConfigurationLogic } from "pages/configuration.slint";

export { CloneLogic, OpenLogic, WorkspacesLogic, ConfigurationLogic }

export component AppWindow inherits Window {
    VerticalBox {
        GroupBox {
            title: "Devmode";
    
            TabWidget {
                Tab {
                    title: "Clone";
                    Clone {}
                }
    
                Tab {
                    title: "Open";
                    Open {}
                }
    
                Tab {
                    title: "Workspaces";
                    Workspaces {
                    }
                }

                Tab {
                    title: "Configuration";
                    Configuration {
                        custom-editor-enabled: false;
                    }
                }
            }
        }
    }
}
